routes:
    /:
        controller: channel
        template: home
        filter: tag:-[hash-email,hash-newsletter-issue]
    /membership/: plans
    /membership/welcome/: welcome
    /membership/welcome-paid/: welcome-premium
    /membership/welcome-friends/: welcome-pro
    /membership/welcome-premium/: welcome-premium
    /membership/welcome-pro/: welcome-pro
    /membership/posts/:
        controller: channel
        template: premium-index
        filter: visibility:[paid,tiers]+tag:-[hash-newsletter-issue,hash-additional-content,hash-email]
    /membership/additional-contents/:
        controller: channel
        template: additional-content-index
        filter: tag:hash-additional-content
    /newsletter/: newsletter
    /newsletter/welcome/: welcome-newsletter
    /login/: login
    /signup/: signup
    /profile/: profile

collections:
    /fr/issues/:
        permalink: /fr/issue/{slug}/
        template: index
        filter: tag:hash-newsletter-issue+tag:hash-fr
    /issues/:
        permalink: /issue/{slug}/
        template: index
        filter: tag:hash-newsletter-issue+tag:hash-en
    /fr/reviews/:
        permalink: /fr/reviews/{slug}/
        template: index
        filter: tag:hash-coffeeshop-review+tag:hash-fr
    /reviews/:
        permalink: /reviews/{slug}/
        template: index
        filter: tag:hash-coffeeshop-review+tag:hash-en
    /fr/posts/:
        permalink: /fr/post/{slug}/
        template: index
        filter: tag:hash-fr+tag:-[hash-email,hash-newsletter-issue,hash-coffeeshop-review,hash-en]
    /posts/:
        permalink: /post/{slug}/
        template: index
        filter: tag:hash-en+tag:-[hash-email,hash-newsletter-issue,hash-coffeeshop-review,hash-fr]

taxonomies:
    tag: /topic/{slug}/
    author: /author/{slug}/
